{% for dp in ['CUSTOMERS', 'SHIPMENTS', 'FLEET', 'LOCATIONS', 'ORDERS', 'PRODUCTS'] %}
DEFINE SCHEMA SFG_LOGISTICS{{env_suffix}}.RAW_{{dp}};
DEFINE SCHEMA SFG_LOGISTICS{{env_suffix}}.STG_{{dp}};
DEFINE SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_{{dp}};
{% endfor %}

DEFINE ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER
    COMMENT = 'Full control for {{dp_name}} domain';

{% for dp in ['CUSTOMERS', 'SHIPMENTS', 'FLEET', 'LOCATIONS', 'ORDERS', 'PRODUCTS'] %}
DEFINE ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_WRITER
    COMMENT = 'RAW + STG read/write for {{dp}} in {{dp_name}}';

DEFINE ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_READER
    COMMENT = 'MART read-only for {{dp}} in {{dp_name}}';

GRANT ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_READER TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_WRITER;
GRANT ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_WRITER TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;

GRANT USAGE ON DATABASE SFG_LOGISTICS{{env_suffix}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_READER;
GRANT USAGE ON SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_READER;

GRANT USAGE ON SCHEMA SFG_LOGISTICS{{env_suffix}}.RAW_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_WRITER;
GRANT USAGE ON SCHEMA SFG_LOGISTICS{{env_suffix}}.STG_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_WRITER;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SFG_LOGISTICS{{env_suffix}}.RAW_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_WRITER;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SFG_LOGISTICS{{env_suffix}}.STG_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_WRITER;
GRANT SELECT ON ALL TABLES IN SCHEMA SFG_LOGISTICS{{env_suffix}}.RAW_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_WRITER;
GRANT SELECT ON ALL TABLES IN SCHEMA SFG_LOGISTICS{{env_suffix}}.STG_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_{{dp}}_WRITER;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SFG_LOGISTICS{{env_suffix}}.RAW_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SFG_LOGISTICS{{env_suffix}}.STG_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;
{% endfor %}

-- OPEN_TRANSPORT: dbt project that reads from RAW_LOCATIONS + RAW_SHIPMENTS (Openflow data)
DEFINE SCHEMA SFG_LOGISTICS{{env_suffix}}.STG_OPEN_TRANSPORT;
DEFINE SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_OPEN_TRANSPORT;

DEFINE ROLE DP_SFG_LOGISTICS{{env_suffix}}_OPEN_TRANSPORT_READER
    COMMENT = 'MART read-only for OPEN_TRANSPORT in {{dp_name}}';

GRANT ROLE DP_SFG_LOGISTICS{{env_suffix}}_OPEN_TRANSPORT_READER TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;

GRANT USAGE ON DATABASE SFG_LOGISTICS{{env_suffix}} TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OPEN_TRANSPORT_READER;
GRANT USAGE ON SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_OPEN_TRANSPORT TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OPEN_TRANSPORT_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_OPEN_TRANSPORT TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OPEN_TRANSPORT_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_OPEN_TRANSPORT TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OPEN_TRANSPORT_READER;

GRANT USAGE ON SCHEMA SFG_LOGISTICS{{env_suffix}}.RAW_LOCATIONS TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;
GRANT USAGE ON SCHEMA SFG_LOGISTICS{{env_suffix}}.RAW_SHIPMENTS TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;
GRANT SELECT ON ALL TABLES IN SCHEMA SFG_LOGISTICS{{env_suffix}}.RAW_LOCATIONS TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;
GRANT SELECT ON ALL TABLES IN SCHEMA SFG_LOGISTICS{{env_suffix}}.RAW_SHIPMENTS TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;

GRANT USAGE ON SCHEMA SFG_LOGISTICS{{env_suffix}}.STG_OPEN_TRANSPORT TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;
GRANT USAGE ON SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_OPEN_TRANSPORT TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SFG_LOGISTICS{{env_suffix}}.STG_OPEN_TRANSPORT TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_OPEN_TRANSPORT TO ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER;

GRANT ROLE DP_SFG_LOGISTICS{{env_suffix}}_OWNER TO ROLE SWISSFLAKES_PLATFORM_ADMIN;

-- Openflow SPCS streaming: SNOWFLAKE_MANAGED auth runs as PUBLIC primary role.
-- Narrow grants so PutSnowpipeStreaming2 can write to pre-created target tables.
GRANT USAGE ON DATABASE SFG_LOGISTICS{{env_suffix}} TO ROLE PUBLIC;
{% for schema in ['RAW_SHIPMENTS', 'RAW_FLEET', 'RAW_LOCATIONS'] %}
GRANT USAGE ON SCHEMA SFG_LOGISTICS{{env_suffix}}.{{schema}} TO ROLE PUBLIC;
GRANT CREATE PIPE ON SCHEMA SFG_LOGISTICS{{env_suffix}}.{{schema}} TO ROLE PUBLIC;
{% endfor %}
GRANT INSERT, EVOLVE SCHEMA ON TABLE SFG_LOGISTICS{{env_suffix}}.RAW_LOCATIONS.TRANSPORT_CONNECTIONS TO ROLE PUBLIC;
GRANT INSERT, EVOLVE SCHEMA ON TABLE SFG_LOGISTICS{{env_suffix}}.RAW_LOCATIONS.SWISSTOPO_BOUNDARIES TO ROLE PUBLIC;
GRANT INSERT, EVOLVE SCHEMA ON TABLE SFG_LOGISTICS{{env_suffix}}.RAW_LOCATIONS.SWISS_PLZ_DIRECTORY TO ROLE PUBLIC;
GRANT INSERT, EVOLVE SCHEMA ON TABLE SFG_LOGISTICS{{env_suffix}}.RAW_SHIPMENTS.SBB_STATIONBOARD TO ROLE PUBLIC;
GRANT INSERT, EVOLVE SCHEMA ON TABLE SFG_LOGISTICS{{env_suffix}}.RAW_SHIPMENTS.SBB_IST_DATEN TO ROLE PUBLIC;
GRANT INSERT, EVOLVE SCHEMA ON TABLE SFG_LOGISTICS{{env_suffix}}.RAW_SHIPMENTS.BAZG_FOREIGN_TRADE TO ROLE PUBLIC;
GRANT INSERT, EVOLVE SCHEMA ON TABLE SFG_LOGISTICS{{env_suffix}}.RAW_FLEET.ASTRA_TRAFFIC_COUNTS TO ROLE PUBLIC;
