DEFINE SCHEMA SFG_ENTERPRISE{{env_suffix}}.RAW_WEATHER;
DEFINE SCHEMA SFG_ENTERPRISE{{env_suffix}}.STG_WEATHER;
DEFINE SCHEMA SFG_ENTERPRISE{{env_suffix}}.MART_WEATHER;

-- Openflow target table: managed by DCM to prevent accidental CREATE OR REPLACE
-- which would invalidate SSV2 pipe bindings.
DEFINE TABLE SFG_ENTERPRISE{{env_suffix}}.RAW_WEATHER.METEOSWISS_MEASUREMENTS (RAW VARIANT);

{% for dp in ['FULFILLMENT', 'CUSTOMER_360', 'REVENUE_ANALYTICS', 'COMPLIANCE'] %}
DEFINE SCHEMA SFG_ENTERPRISE{{env_suffix}}.MART_{{dp}};
{% endfor %}

DEFINE ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER
    COMMENT = 'Full control for {{dp_name}} domain';

{% for dp in ['FULFILLMENT', 'CUSTOMER_360', 'REVENUE_ANALYTICS', 'COMPLIANCE'] %}
DEFINE ROLE DP_SFG_ENTERPRISE{{env_suffix}}_{{dp}}_READER
    COMMENT = 'MART read-only for {{dp}} in {{dp_name}}';

GRANT ROLE DP_SFG_ENTERPRISE{{env_suffix}}_{{dp}}_READER TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;

GRANT USAGE ON DATABASE SFG_ENTERPRISE{{env_suffix}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_{{dp}}_READER;
GRANT USAGE ON SCHEMA SFG_ENTERPRISE{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_{{dp}}_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA SFG_ENTERPRISE{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_{{dp}}_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SFG_ENTERPRISE{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_{{dp}}_READER;

GRANT CREATE TABLE, CREATE VIEW, CREATE SEMANTIC VIEW ON SCHEMA SFG_ENTERPRISE{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;
{% endfor %}

-- WEATHER: dbt project that reads from RAW_WEATHER (Openflow data)
DEFINE ROLE DP_SFG_ENTERPRISE{{env_suffix}}_WEATHER_READER
    COMMENT = 'MART read-only for WEATHER in {{dp_name}}';

GRANT ROLE DP_SFG_ENTERPRISE{{env_suffix}}_WEATHER_READER TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;

GRANT USAGE ON DATABASE SFG_ENTERPRISE{{env_suffix}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_WEATHER_READER;
GRANT USAGE ON SCHEMA SFG_ENTERPRISE{{env_suffix}}.MART_WEATHER TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_WEATHER_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA SFG_ENTERPRISE{{env_suffix}}.MART_WEATHER TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_WEATHER_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SFG_ENTERPRISE{{env_suffix}}.MART_WEATHER TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_WEATHER_READER;

GRANT USAGE ON SCHEMA SFG_ENTERPRISE{{env_suffix}}.RAW_WEATHER TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;
GRANT SELECT ON ALL TABLES IN SCHEMA SFG_ENTERPRISE{{env_suffix}}.RAW_WEATHER TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;

GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SFG_ENTERPRISE{{env_suffix}}.STG_WEATHER TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SFG_ENTERPRISE{{env_suffix}}.MART_WEATHER TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;

GRANT USAGE ON DATABASE SFG_LOGISTICS{{env_suffix}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;
GRANT USAGE ON DATABASE SFG_PAY{{env_suffix}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;

{% for dp in ['CUSTOMERS', 'SHIPMENTS', 'FLEET', 'LOCATIONS', 'ORDERS', 'PRODUCTS', 'OPEN_TRANSPORT'] %}
GRANT USAGE ON SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;
GRANT SELECT ON ALL TABLES IN SCHEMA SFG_LOGISTICS{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;
{% endfor %}

{% for dp in ['TRANSACTIONS', 'MERCHANTS'] %}
GRANT USAGE ON SCHEMA SFG_PAY{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;
GRANT SELECT ON ALL TABLES IN SCHEMA SFG_PAY{{env_suffix}}.MART_{{dp}} TO ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER;
{% endfor %}

GRANT ROLE DP_SFG_ENTERPRISE{{env_suffix}}_OWNER TO ROLE SWISSFLAKES_PLATFORM_ADMIN;

GRANT USAGE ON DATABASE SFG_ENTERPRISE{{env_suffix}} TO ROLE OPENFLOW_ADMIN;
GRANT USAGE ON SCHEMA SFG_ENTERPRISE{{env_suffix}}.RAW_WEATHER TO ROLE OPENFLOW_ADMIN;
GRANT CREATE PIPE ON SCHEMA SFG_ENTERPRISE{{env_suffix}}.RAW_WEATHER TO ROLE OPENFLOW_ADMIN;

-- Openflow SPCS streaming: SNOWFLAKE_MANAGED auth runs as PUBLIC primary role.
-- Narrow grants so PutSnowpipeStreaming2 can write to pre-created target tables.
GRANT USAGE ON DATABASE SFG_ENTERPRISE{{env_suffix}} TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA SFG_ENTERPRISE{{env_suffix}}.RAW_WEATHER TO ROLE PUBLIC;
GRANT CREATE PIPE ON SCHEMA SFG_ENTERPRISE{{env_suffix}}.RAW_WEATHER TO ROLE PUBLIC;
GRANT INSERT, EVOLVE SCHEMA ON TABLE SFG_ENTERPRISE{{env_suffix}}.RAW_WEATHER.METEOSWISS_MEASUREMENTS TO ROLE PUBLIC;
