name: sfg_enterprise_fulfillment
version: '1.0.0'

profile: sfg_enterprise_fulfillment

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

clean-targets:
  - target
  - dbt_packages

models:
  sfg_enterprise_fulfillment:
    marts:
      +schema: MART_FULFILLMENT
      +materialized: table
    semantic_views:
      +schema: MART_FULFILLMENT
      +materialized: semantic_view
