DEFINE SCHEMA SFG_ADMIN{{env_suffix}}.GOVERNANCE;
DEFINE SCHEMA SFG_ADMIN{{env_suffix}}.AGENTS;

DEFINE TAG SFG_ADMIN{{env_suffix}}.GOVERNANCE.DATA_QUALITY
    ALLOWED_VALUES 'BRONZE', 'SILVER', 'GOLD'
    COMMENT = 'Data quality tier for schemas and tables';

DEFINE TAG SFG_ADMIN{{env_suffix}}.GOVERNANCE.PII_LEVEL
    ALLOWED_VALUES 'NONE', 'LOW', 'MEDIUM', 'HIGH'
    COMMENT = 'PII sensitivity classification';

DEFINE TAG SFG_ADMIN{{env_suffix}}.GOVERNANCE.DATA_DOMAIN
    ALLOWED_VALUES 'LOGISTICS', 'PAYMENTS', 'COMMERCE', 'COMPLIANCE', 'ANALYTICS'
    COMMENT = 'Business domain classification';

DEFINE TAG SFG_ADMIN{{env_suffix}}.GOVERNANCE.DATA_OWNER
    COMMENT = 'Data product owner team or person';

DEFINE TAG SFG_ADMIN{{env_suffix}}.GOVERNANCE.RETENTION_DAYS
    COMMENT = 'Data retention period in days';

DEFINE TAG SFG_ADMIN{{env_suffix}}.GOVERNANCE.REGULATION
    ALLOWED_VALUES 'BAZG', 'FINMA', 'DSG', 'PCI_DSS', 'GWG', 'NONE'
    COMMENT = 'Applicable regulatory framework';

DEFINE TAG SFG_ADMIN{{env_suffix}}.GOVERNANCE.COST_CENTER
    COMMENT = 'Cost center for chargeback';

DEFINE TAG SFG_ADMIN{{env_suffix}}.GOVERNANCE.ENVIRONMENT
    ALLOWED_VALUES 'DEV', 'TEST', 'PROD'
    COMMENT = 'Deployment environment';

DEFINE TAG SFG_ADMIN{{env_suffix}}.GOVERNANCE.CLASSIFICATION
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'
    COMMENT = 'Data classification level';

DEFINE WAREHOUSE SWISSFLAKES_WH_LOAD
WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    COMMENT = 'Data loading and ingestion';

DEFINE WAREHOUSE SWISSFLAKES_WH_TRANSFORM
WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    COMMENT = 'dbt and dynamic table transformations';

DEFINE WAREHOUSE SWISSFLAKES_WH_BI
WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    COMMENT = 'BI and reporting queries';

DEFINE WAREHOUSE SWISSFLAKES_WH_CORTEX
WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    COMMENT = 'Cortex AI functions and agents';

DEFINE WAREHOUSE SWISSFLAKES_WH_COMPLIANCE
WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    COMMENT = 'Compliance and audit queries';

DEFINE WAREHOUSE SWISSFLAKES_WH_ADMIN
WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    COMMENT = 'Administrative tasks';

DEFINE WAREHOUSE SWISSFLAKES_WH_GENERAL
WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    COMMENT = 'General purpose queries';

DEFINE WAREHOUSE SWISSFLAKES_WH_OPENFLOW
WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    COMMENT = 'Openflow connector execution';
