DEFINE ROLE SWISSFLAKES_PLATFORM_ADMIN
    COMMENT = 'Platform administrator - full access to all data products';

DEFINE ROLE SWISSFLAKES_DATA_ENGINEER
    COMMENT = 'Data engineer - builds and maintains pipelines';

DEFINE ROLE SWISSFLAKES_DATA_ANALYST
    COMMENT = 'Data analyst - reads marts, runs queries';

DEFINE ROLE SWISSFLAKES_COMPLIANCE_OFFICER
    COMMENT = 'Compliance officer - BAZG, FINMA, DSG audit access';

DEFINE ROLE SWISSFLAKES_CORTEX_ANALYST
    COMMENT = 'Cortex user - semantic views and agent access';

DEFINE ROLE SWISSFLAKES_BI_CONSUMER
    COMMENT = 'BI consumer - read-only marts access';

GRANT ROLE SWISSFLAKES_BI_CONSUMER TO ROLE SWISSFLAKES_DATA_ANALYST;
GRANT ROLE SWISSFLAKES_DATA_ANALYST TO ROLE SWISSFLAKES_DATA_ENGINEER;
GRANT ROLE SWISSFLAKES_DATA_ENGINEER TO ROLE SWISSFLAKES_PLATFORM_ADMIN;
GRANT ROLE SWISSFLAKES_COMPLIANCE_OFFICER TO ROLE SWISSFLAKES_PLATFORM_ADMIN;
GRANT ROLE SWISSFLAKES_CORTEX_ANALYST TO ROLE SWISSFLAKES_DATA_ANALYST;
GRANT ROLE SWISSFLAKES_PLATFORM_ADMIN TO ROLE SYSADMIN;

DEFINE ROLE SFG_LOGISTICS_DATA_PUBLISHER
    COMMENT = 'Grants listing and share creation privileges to SwissFlakes Logistics AG';

DEFINE ROLE SFG_PAY_DATA_PUBLISHER
    COMMENT = 'Grants listing and share creation privileges to SwissFlakes Pay AG';

GRANT ROLE SFG_LOGISTICS_DATA_PUBLISHER TO ROLE SWISSFLAKES_PLATFORM_ADMIN;
GRANT ROLE SFG_PAY_DATA_PUBLISHER TO ROLE SWISSFLAKES_PLATFORM_ADMIN;

GRANT CREATE SHARE ON ACCOUNT TO ROLE SFG_LOGISTICS_DATA_PUBLISHER;
GRANT CREATE ORGANIZATION LISTING ON ACCOUNT TO ROLE SFG_LOGISTICS_DATA_PUBLISHER;
GRANT IMPORT SHARE ON ACCOUNT TO ROLE SFG_LOGISTICS_DATA_PUBLISHER;

GRANT CREATE SHARE ON ACCOUNT TO ROLE SFG_PAY_DATA_PUBLISHER;
GRANT CREATE ORGANIZATION LISTING ON ACCOUNT TO ROLE SFG_PAY_DATA_PUBLISHER;
GRANT IMPORT SHARE ON ACCOUNT TO ROLE SFG_PAY_DATA_PUBLISHER;

GRANT USAGE ON WAREHOUSE SWISSFLAKES_WH_LOAD TO ROLE SWISSFLAKES_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE SWISSFLAKES_WH_TRANSFORM TO ROLE SWISSFLAKES_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE SWISSFLAKES_WH_BI TO ROLE SWISSFLAKES_DATA_ANALYST;
GRANT USAGE ON WAREHOUSE SWISSFLAKES_WH_CORTEX TO ROLE SWISSFLAKES_CORTEX_ANALYST;
GRANT USAGE ON WAREHOUSE SWISSFLAKES_WH_COMPLIANCE TO ROLE SWISSFLAKES_COMPLIANCE_OFFICER;
GRANT USAGE ON WAREHOUSE SWISSFLAKES_WH_ADMIN TO ROLE SWISSFLAKES_PLATFORM_ADMIN;
GRANT USAGE ON WAREHOUSE SWISSFLAKES_WH_GENERAL TO ROLE SWISSFLAKES_BI_CONSUMER;
GRANT USAGE ON WAREHOUSE SWISSFLAKES_WH_OPENFLOW TO ROLE SWISSFLAKES_DATA_ENGINEER;

GRANT USAGE ON DATABASE SFG_ADMIN{{env_suffix}} TO ROLE SWISSFLAKES_PLATFORM_ADMIN;
GRANT USAGE ON SCHEMA SFG_ADMIN{{env_suffix}}.GOVERNANCE TO ROLE SWISSFLAKES_PLATFORM_ADMIN;
GRANT USAGE ON SCHEMA SFG_ADMIN{{env_suffix}}.AGENTS TO ROLE SWISSFLAKES_PLATFORM_ADMIN;
GRANT USAGE ON SCHEMA SFG_ADMIN{{env_suffix}}.AGENTS TO ROLE SWISSFLAKES_CORTEX_ANALYST;
